[project]
name = "myfast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.8",
    "fastapi-cli>=0.0.7",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
]
